name: Fetch data, generate index, build website and deploy to github pages
# defines when the action should be executed in this case on push to the main branch or manual trigger
on:
  schedule:
    - cron: "41 3 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v6 

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-utils
          xmllint --version

      - name: set up node.js 
        uses: actions/setup-node@v6
        with:
          node-version: 22 

      - name: enable corepack
        run: |
          corepack enable
          corepack install
      
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile    

     
      - name: fetch fresh data using script
        run: pnpm run fetch-data 

      - name: data processing 
        run: |
          echo "Processing data..."
          pnpm run process-data

      - name: generate typesense index
        env:
          TYPESENSE_ADMIN_API_KEY: ${{ secrets.TYPESENSE_ADMIN_API_KEY }}
          PUBLIC_TYPESENSE_API_HOST: ${{ secrets.PUBLIC_TYPESENSE_API_HOST }}
          PUBLIC_TYPESENSE_API_PORT: ${{ secrets.PUBLIC_TYPESENSE_API_PORT }}
          PUBLIC_TYPESENSE_API_PROTOCOL: ${{ secrets.PUBLIC_TYPESENSE_API_PROTOCOL }}
        run: pnpm run generate-index

      - name: setup pages
        id: pages
        uses: actions/configure-pages@v6
        with:
          enablement: true

      - name: build website
        env:
            BASE_PATH: '/${{ github.event.repository.name }}'
       
        run: pnpm run build

      - name: upload artifacts
        uses: actions/upload-pages-artifact@v5
        with:
          path: 'build/'

      - name: Deploy to Github pages
        if: github.event_name != 'push'
        id: deployment
        uses: actions/deploy-pages@v5
